
/* Drop Triggers */

DROP TRIGGER TRI_T_APP_APP_ID;
DROP TRIGGER TRI_T_BOOK_BOOK_ID;
DROP TRIGGER TRI_T_NOTICE_NOTICE_ID;
DROP TRIGGER TRI_T_RESERVATION_RESER_ID;
DROP TRIGGER TRI_T_SUGGEST_SUGGES_ID;



/* Drop Tables */

DROP TABLE T_APP CASCADE CONSTRAINTS;
DROP TABLE T_RENT CASCADE CONSTRAINTS;
DROP TABLE T_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE T_BOOK CASCADE CONSTRAINTS;
DROP TABLE T_SUGGEST CASCADE CONSTRAINTS;
DROP TABLE T_MEMBER CASCADE CONSTRAINTS;
DROP TABLE T_NOTICE CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_T_APP_APP_ID;
DROP SEQUENCE SEQ_T_BOOK_BOOK_ID;
DROP SEQUENCE SEQ_T_NOTICE_NOTICE_ID;
DROP SEQUENCE SEQ_T_RESERVATION_RESER_ID;
DROP SEQUENCE SEQ_T_SUGGEST_SUGGES_ID;




/* Create Sequences */

CREATE SEQUENCE SEQ_T_APP_APP_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_T_BOOK_BOOK_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_T_NOTICE_NOTICE_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_T_RESERVATION_RESER_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_T_SUGGEST_SUGGES_ID INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE T_APP
(
	APP_ID number NOT NULL,
	APPROVAL char DEFAULT 'N',
	BOOK_NAME varchar2(100) NOT NULL,
	AUTHOR varchar2(100) NOT NULL,
	PUBLISHER varchar2(100) NOT NULL,
	APP_DATE date DEFAULT SYSDATE NOT NULL,
	ID varchar2(50) NOT NULL,
	PRIMARY KEY (APP_ID)
);


CREATE TABLE T_BOOK
(
	BOOK_ID number NOT NULL,
	BOOK_NAME varchar2(200) NOT NULL,
	AUTHOR varchar2(100) NOT NULL,
	PUBLISHER varchar2(100) NOT NULL,
	REG_DATE date NOT NULL,
	RESER_NUM number DEFAULT 0 NOT NULL,
	RENT_AVAIL char DEFAULT 'Y' NOT NULL,
	PRIMARY KEY (BOOK_ID)
);


CREATE TABLE T_MEMBER
(
	ID varchar2(50) NOT NULL,
	PW varchar2(500) NOT NULL,
	NAME varchar2(100) NOT NULL,
	PHONE varchar2(100),
	ADDRESS varchar2(250),
	JOIN_DATE date DEFAULT SYSDATE NOT NULL,
	OVERDUE char DEFAULT 'N',
	PRIMARY KEY (ID)
);


CREATE TABLE T_NOTICE
(
	NOTICE_ID number NOT NULL,
	TITLE varchar2(100) NOT NULL,
	CONTENT varchar2(1000) NOT NULL,
	RED_DATE date DEFAULT SYSDATE NOT NULL,
	MOD_DATE date,
	PRIMARY KEY (NOTICE_ID)
);


CREATE TABLE T_RENT
(
	RENT_ID number NOT NULL,
	RENT_DATE date DEFAULT SYSDATE NOT NULL,
	RETURN_DATE date,
	RETURN_DEADLINE date DEFAULT SYSDATE + 13 NOT NULL,
	BOOK_ID number,
	ID varchar2(50) NOT NULL,
	PRIMARY KEY (RENT_ID)
);


CREATE TABLE T_RESERVATION
(
	RESER_ID number NOT NULL,
	RESER_DATE date NOT NULL,
	ID varchar2(50) NOT NULL,
	BOOK_ID number,
	PRIMARY KEY (RESER_ID)
);


CREATE TABLE T_SUGGEST
(
	SUGGES_ID number NOT NULL,
	TITLE varchar2(500) NOT NULL,
	CONTENT varchar2(1000) NOT NULL,
	RED_DATE date DEFAULT SYSDATE NOT NULL,
	MOD_DATE date,
	REPLY varchar2(500),
	CHECKED char DEFAULT 'N',
	ID varchar2(50) NOT NULL,
	PRIMARY KEY (SUGGES_ID)
);



/* Create Foreign Keys */

ALTER TABLE T_RENT
	ADD FOREIGN KEY (BOOK_ID)
	REFERENCES T_BOOK (BOOK_ID)
;


ALTER TABLE T_RESERVATION
	ADD FOREIGN KEY (BOOK_ID)
	REFERENCES T_BOOK (BOOK_ID)
;


ALTER TABLE T_APP
	ADD FOREIGN KEY (ID)
	REFERENCES T_MEMBER (ID)
;


ALTER TABLE T_RENT
	ADD FOREIGN KEY (ID)
	REFERENCES T_MEMBER (ID)
;


ALTER TABLE T_RESERVATION
	ADD FOREIGN KEY (ID)
	REFERENCES T_MEMBER (ID)
;


ALTER TABLE T_SUGGEST
	ADD FOREIGN KEY (ID)
	REFERENCES T_MEMBER (ID)
;




